CONCEPTS_SCORES = {
    "intern": {
        "Seniority": 0,
        "Max Programming Language": 2,
        "Max Tool/Framework": 4,
        "Max Certification": 2,
        "Max Programming Concept": 8,
        "Max IT Specialization": 0,
        "Full Programming Language": 7,
        "Partial Programming Language": 3,
        "Full Tool/Framework": 3,
        "Partial Tool/Framework": 1.5,
        "Full Certification": 0,
        "Partial Certification": 0,
        "Full Programming Concept": 5,
        "Partial Programming Concept": 3,
        "Full IT Specialization": 0,
        "Partial IT Specialization": 0
    },
    "junior": {
        "Seniority": 1,
        "Max Programming Language": 4,
        "Max Tool/Framework": 8,
        "Max Certification": 3,
        "Max Programming Concept": 10,
        "Max IT Specialization": 2,
        "Full Programming Language": 7,
        "Partial Programming Language": 3,
        "Full Tool/Framework": 5,
        "Partial Tool/Framework": 2,
        "Full Certification": 1,
        "Partial Certification": 0.5,
        "Full Programming Concept": 3,
        "Partial Programming Concept": 1.5,
        "Full IT Specialization": 1,
        "Partial IT Specialization": 0.5
    },
    "mid": {
        "Seniority": 2,
        "Max Programming Language": 6,
        "Max Tool/Framework": 12,
        "Max Certification": 4,
        "Max Programming Concept": 12,
        "Max IT Specialization": 3,
        "Full Programming Language": 5,
        "Partial Programming Language": 2,
        "Full Tool/Framework": 7,
        "Partial Tool/Framework": 3,
        "Full Certification": 3,
        "Partial Certification": 1.5,
        "Full Programming Concept": 2,
        "Partial Programming Concept": 1,
        "Full IT Specialization": 3,
        "Partial IT Specialization": 1.5
    },
    "senior": {
        "Seniority": 3,
        "Max Programming Language": 8,
        "Max Tool/Framework": 15,
        "Max Certification": 4,
        "Max Programming Concept": 15,
        "Max IT Specialization": 4,
        "Full Programming Language": 5,
        "Partial Programming Language": 2,
        "Full Tool/Framework": 7,
        "Partial Tool/Framework": 3,
        "Full Certification": 4,
        "Partial Certification": 2,
        "Full Programming Concept": 2,
        "Partial Programming Concept": 1,
        "Full IT Specialization": 3,
        "Partial IT Specialization": 1.5
    }
}